create type kana_alphabet as enum ('hiragana', 'katakana');
create type mastery_status as enum ('new', 'learning', 'familiar', 'strong', 'mastered');
create table profiles (id uuid primary key references auth.users(id) on delete cascade, username text not null, avatar_url text, xp integer not null default 0, daily_goal integer not null default 15, progress_data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table profiles add column if not exists progress_data jsonb not null default '{}'::jsonb;
create table kana (id text primary key, character text not null, romaji text not null, alphabet kana_alphabet not null, group_name text not null, sort_order integer not null, pronunciation text not null, example_word text not null, example_reading text not null, meaning text not null);
create table lessons (id bigint generated always as identity primary key, alphabet kana_alphabet not null, title text not null, sort_order integer not null);
create table lesson_progress (user_id uuid references profiles(id) on delete cascade, lesson_id bigint references lessons(id) on delete cascade, status text not null default 'locked', completed_at timestamptz, primary key(user_id, lesson_id));
create table user_kana_progress (user_id uuid references profiles(id) on delete cascade, kana_id text references kana(id) on delete cascade, mastery_score smallint not null default 0 check (mastery_score between 0 and 100), correct_answers integer not null default 0, incorrect_answers integer not null default 0, current_streak integer not null default 0, last_reviewed timestamptz, next_review timestamptz, status mastery_status not null default 'new', primary key(user_id, kana_id));
create table practice_sessions (id uuid primary key default gen_random_uuid(), user_id uuid references profiles(id) on delete cascade, mode text not null, started_at timestamptz not null default now(), ended_at timestamptz, accuracy numeric, xp_earned integer not null default 0);
create table practice_answers (id bigint generated always as identity primary key, session_id uuid references practice_sessions(id) on delete cascade, kana_id text references kana(id), is_correct boolean not null, response_ms integer not null, created_at timestamptz not null default now());
create table achievements (id text primary key, title text not null, description text not null, xp_reward integer not null default 0);
create table user_achievements (user_id uuid references profiles(id) on delete cascade, achievement_id text references achievements(id) on delete cascade, unlocked_at timestamptz not null default now(), primary key(user_id, achievement_id));
create table streaks (user_id uuid primary key references profiles(id) on delete cascade, current_streak integer not null default 0, longest_streak integer not null default 0, last_study_date date);
alter table profiles enable row level security; alter table user_kana_progress enable row level security; alter table lesson_progress enable row level security; alter table practice_sessions enable row level security; alter table practice_answers enable row level security; alter table user_achievements enable row level security; alter table streaks enable row level security;
create policy "users own profile" on profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "users own kana progress" on user_kana_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own lesson progress" on lesson_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own sessions" on practice_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own achievements" on user_achievements for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users own streak" on streaks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
